```{r}
library(dplyr)
library(caret)
library(lme4)
set.seed(123)
```


Load data function
```{r}
read_data <- function() {
  data <- read.csv("./data/star_data.csv")
  df <- na.omit(data)
  
  colnames(df) <- c("tmp", "mh", "logg", "mag", "ra", "dec", "par", "ra_e", "dec_e", "par_e", "logg_low", "logg_up", "mh_low", "mh_up","tmp_low", "tmp_up", "blue_mag", "red_mag", "rad_vel")

  #make confidence intervals for mh and logg
  df$int_mh <- df$mh_up - df$mh_low
  df$int_logg <- df$logg_up - df$logg_low
  df$int_tmp <- df$tmp_up - df$tmp_low
  
  #calculate distance
  df$d <- abs(1000/df$par)
  
  #convert apparent mag to absolute
  df$mag <- df$mag - 5*log10(df$d) + 5
  
  #calculate luminosity
  l_sun <- 3.828e26
  df$l <- l_sun * 10^((4.83-df$mag)/2.5)
  
  #extract coordinate data and corresponding errors
  coords <- df |>
    filter(abs(d) < 25000, int_tmp < 24, int_mh < 0.0476, int_logg < 0.025) |>
    select(ra, dec, par, par_e, dec_e, ra_e, d)
  
  coords$ra_rad <- coords$ra*pi/180
  coords$dec_rad <- coords$dec*pi/180
  
  coords$x <- coords$d * cos(coords$dec_rad) * cos(coords$ra_rad)
  coords$y <- coords$d * cos(coords$dec_rad) * sin(coords$ra_rad)
  coords$z <- coords$d * sin(coords$dec_rad)
  
  coords <- coords |> filter(z<0)
  #remove used columns for space efficiency
  df <- df |> 
    filter(abs(d) < 25000, int_tmp < 24, int_mh < 0.0476, int_logg < 0.025, par_e < 0.0132) |>
    select(tmp, d, mh, logg, mag, l, blue_mag, red_mag, rad_vel) 
  
  #preproc_l <- preProcess(df, method = c("center", "scale"))
  #df <- predict(preproc_l, df)
  coords <- coords[1:300,]
  return(df)
}
```

Run Linear Model

```{r}
df<-read_data()
model_l <- lm(mh ~ d + tmp + logg + mag + l + blue_mag + red_mag + rad_vel, data = df)
summary(model_l)

ggplot(df, aes(x = mag, y = mh)) +
  geom_point() +     
  labs(x = 'Temperature (K)', y='Metallicity [Fe/H]', title = 'Linear Relationship Between Temperature and Metallicity') +
  geom_smooth(method = "lm",         
  formula = y ~ x,       
  color = "blue",         
  se = TRUE)
```

Create Binary Classification
```{r}
df <- read_data()
df$bin <- factor(ifelse(df$mh > -0.2212, 1, 0))


```






Create hierarchy
```{r}
summary(df$d)
df$levels <- 0
df$levels <- ifelse(df$d > 331.28 & df$d <= 471.47, 1, df$levels)
df$levels <- ifelse(df$d > 471.47 & df$d <= 654.54, 2, df$levels)
df$levels <- ifelse(df$d > 653.54, 3, df$levels)
levels <- factor(df$levels)
```


Run Linear Mixed Effects Model
null hypotheses: the mean values of the differnt groups do not differ, one factor has no influence on the effect of the other factor
```{r}
preproc_l <- preProcess(df, method = c("center", "scale"))
df_norm <- predict(preproc_l, df)
df_norm <- df_norm |> select(-levels)
df_norm <- cbind(df_norm, levels)
model_lme <- lmer(mh ~ tmp + logg + mag + blue_mag + red_mag + (1 | levels), data = df_norm)
summary(model_lme)
AIC(model_l, model_lme)
BIC(model_l, model_lme)

df$levels<-factor(df$levels)
ggplot(df, aes(x = mh, fill = levels)) +
  geom_density(alpha = 0.5) +  # alpha for transparency
  labs(title = "Distribution of Metallicity Values Grouped by Distance", x = "Metallicity", y = "Density") +
  scale_fill_manual(values = c("red", "blue", "green", "purple")) +  # Custom colors
  theme_minimal()
```


https://www.sciencedirect.com/science/article/pii/S2213133715000360
https://arxiv.org/pdf/1707.05834    
https://ned.ipac.caltech.edu/level5/Wall2/Wal3_1.html
1929 paper











